site_name: Zephyr
pages:
- Zephyr: index.md
- FileSystem:
  - Introduction: FileSystem/index.md
  - Utilities: FileSystem/utilities.md
  - Implementations:
    - Windows: FileSystem/windows.md
    - Amazon S3: FileSystem/amazons3.md
theme: readthedocs